# Configuración de build
[build]
  command = "npm run build"
  publish = "dist"
a
  [build.environment]
    NODE_VERSION = "20"

# Redirección importante para React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

